#!/usr/bin/env python3
from pybpodapi.protocol import Bpod
from mouse import Mouse
from mouse2afc import Mouse2AFC


def main():
    bpod = Bpod(emulator_mode=True)
    mouse = Mouse(bpod)
    mouse.spawn()
    Mouse2AFC(bpod).run()


if __name__ == '__main__':
    main()
