#!/usr/bin/env python3
"Runs mouse2afc without a physical Bpod nor Pybpod, with input from a 'virtual mouse' "
from pybpodapi.protocol import Bpod
from virutal_mouse import Mouse
from mouse2afc.mouse2afc import Mouse2AFC

def main():
    bpod = Bpod(emulator_mode=True)
    mouse = Mouse(bpod)
    mouse.spawn()
    Mouse2AFC(bpod).run()


if __name__ == '__main__':
    main()
