#!/usr/bin/env python3
"Runs mouse2afc on a physical Bpod without pybpod"
from pybpodapi.protocol import Bpod
from mouse2afc import Mouse2AFC


def main():
    bpod = Bpod(emulator_mode=True)
    Mouse2AFC(bpod).run()


if __name__ == '__main__':
    main()
